# Generated by Django 4.2.1 on 2023-09-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField(max_length=600)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("bando", "Bando"),
                            ("altro", "Altro"),
                        ],
                        default="altro",
                        max_length=10,
                    ),
                ),
                ("value", models.IntegerField()),
                ("new", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
