# Generated by Django 4.2.1 on 2023-09-20 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio_agronomico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
