# Generated by Django 4.2.1 on 2023-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_agronomico", "0003_userprofile_followed_blogposts"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="ref_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="desc",
            field=models.TextField(max_length=2500),
        ),
    ]
